# Refer https://github.com/volatiletech/sqlboiler#configuration
schema = "public"
pkgname = "orm"
output = "internal/adapters/repository/orm"
wipe = true
no-tests = true
no-hooks = true

[psql]
    dbname = "alchemist-template"
    host = "pg"
    port = "5432"
    user = "alchemist-template"
    pass = ""
    sslmode = "disable"
    whitelist = ["users"]
